spring:
  application:
    name: backend
  profiles:
    active: dev  # 기본 활성 프로필 (dev 또는 prod)
  cache:
    type: none
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      timeout: 30m
      cookie:
        http-only: true
        same-site: lax
      tracking-modes: cookie
  security:
    cors:
      allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false
        same-site: lax
      tracking-modes: cookie 