spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  security:
    cors:
      allowed-origins: https://yourproductiondomain.com
  servlet:
    session:
      cookie:
        secure: true  # 운영 환경에서는 HTTPS 필수

server:
  servlet:
    session:
      timeout: 1h  # 운영 환경에서는 세션 타임아웃 1시간

logging:
  level:
    root: WARN
    com.backend.backend: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN 